server:
  port: 9082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:order_service_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS order_service_db
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
  flyway:
    locations: "classpath:/db/migration"

  #TODO: change sleuth sample probability
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  #TODO: add zipkin configs for local
  zipkin:
    base-url: http://zipkin.team-i.cloud.school.thoughtworks.cn
#TODO: change servlet log level to view the logs
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
logging:
  level:
    org.springframework.web: debug
